### ISSUE TITLE
大佬求教

### ISSUE THREAD

**Issue by shandongtlb** [mengxianghan/xy-admin#1]
大佬你好，请问你这个项目有没有匹配的后端呢，另外，如果没有的话，您之前的cms_vue2的项目对应的后端能否应用在本前端项目上呢

大佬有没有交流群啊

**Comment by mengxianghan** [comment]
1. 这是纯前端的项目，没有对应后端
2. cms_vue2 的项目后端和此项目是不匹配的
3. 目前用户较少，还没有交流群

**Comment by shandongtlb** [comment]
好的，谢谢，现在在用你的cms那个项目，一切正常，太感谢了！
