### ISSUE TITLE
demo 地址无发登录

### ISSUE THREAD

**Issue by jiahaowu-git** [mengxianghan/xy-admin#1]
默认 admin/123456 无法登录

**Comment by mengxianghan** [comment]
这个项目的mock没做使用vue3推荐的方式，如果无法登录可以刷新后重试

**Comment by mengxianghan** [comment]
1.这个是纯前端项目，暂时没有对应的后端2.cms_vue2后端的数据结构和xy-admin的有些不同，或者并不适用于本项目3.目前还没有交流群，您可以先添加我的微信  微信号：meng_xianghan 孟祥涵在 2023年1月9日，08:47，SDTLB ***@***.***> 写道：﻿
大佬你好，请问你这个项目有没有匹配的后端呢，另外，如果没有的话，您之前的cms_vue2的项目对应的后端能否应用在本前端项目上呢
大佬有没有交流群啊

**Comment by jiahaowu-git** [comment]
嗯，刷新可以了。做的挺不错的，支持！
