### ISSUE TITLE
关于侧边栏收缩按钮位置问题

### ISSUE THREAD

**Issue by sincely** [mengxianghan/xy-admin#3]
![WX20231215-231514@2x](https://github.com/mengxianghan/xy-admin/assets/40814642/9b8c018d-4bc7-4eb7-a85b-2ee1e974c2d3)
可以定义侧边栏收缩按钮位置吗？

**Comment by sincely** [comment]
我司正在用楼主的开源框架，能开捐赠通道吗？开源不易！！深有体会

**Comment by mengxianghan** [comment]
> ![WX20231215-231514@2x](https://private-user-images.githubusercontent.com/40814642/290861502-9b8c018d-4bc7-4eb7-a85b-2ee1e974c2d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2ODk4NjAsIm5iZiI6MTcwMjY4OTU2MCwicGF0aCI6Ii80MDgxNDY0Mi8yOTA4NjE1MDItOWI4YzAxOGQtNGJjNy00ZWI3LWE4NWItMmVlMWU5NzRjMmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDAxMTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiZDMwZGM1MjFjZjkxZjQyNDU4NWJmOTYxZjMzZjY2MjBhZDZkNWJhOTkwOGVmNjE5MDc2MGZiZDAxZDcwMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6iTYnZFgz0H7II5tgFe1PlgddLXixGDCgEgajRjgniM)可以定义侧边栏收缩按钮位置吗？

目前定义收缩按钮位置稍微有所复杂，可以关注近期更新，会将侧边收缩控制属性移动至 store

**Comment by sincely** [comment]
感谢！！！！
