### ISSUE TITLE
项目主题色混入方法设计

### ISSUE THREAD

**Issue by sincely** [mengxianghan/xy-admin#4]
<img width="1304" alt="image" src="https://github.com/mengxianghan/xy-admin/assets/40814642/fc26dfaa-58fd-40cb-ac7f-350f4bd0de47">
我水平可能没有楼主高，项目这3个less文件,仔细看下来是切换项目主题颜色，这个混入方法太难阅读了，和理解了，

**Comment by mengxianghan** [comment]
> <img width="1304" alt="image" src="https://github.com/mengxianghan/xy-admin/assets/40814642/fc26dfaa-58fd-40cb-ac7f-350f4bd0de47">
> 
> 我水平可能没有楼主高，项目这3个less文件,仔细看下来是切换项目主题颜色，这个混入方法太难阅读了，和理解了，

这个是从ant design 组件库中提取出来的，只是为了生成和组件库统一的色板，会使用即可，可以不用理解内部原理
