### ISSUE TITLE
从登陆页面进入项目首页， 点击浏览器返回（回退到上一个页面导航），最终返回到登陆页面！

### ISSUE THREAD

**Issue by sincely** [mengxianghan/xy-admin#6]
复现步骤如下：
1：从登陆页面进入项目首页，
2：按照permission逻辑，登陆完成之后已经保留了登陆状态信息，点击浏览器返回（回退到上一个页面导航），
3：最终结果回到了登陆界面，这个应该是个bug，无需在返回到登陆页面，应该回到首页
类似demo链接 

> ( https://antd.soybeanjs.cn/login?redirect=/home )

**Comment by mengxianghan** [comment]
这个可以根据自己的业务逻辑进行处理，如果不需要返回到登录页可以将 `src/store/modules/user.js` 中 `119` 行的 `router.push` 更改为 `router.replace`

**Comment by sincely** [comment]
感谢
